apiVersion: apps/v1
kind: Deployment
metadata:
  name: endpoint-frontend
  namespace: endpoint
spec:
  replicas: 1
  selector:
    matchLabels:
      app: endpoint-frontend
  template:
    metadata:
      labels:
        app: endpoint-frontend
    spec:
      containers:
        - name: frontend
          image: 192.168.10.102/xiaoshuowang/frontend:1b58bbc4c474edbdb6e3e9e977e761b719224d73
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 500m
              memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: endpoint-frontend-svc
  namespace: endpoint
spec:
  type: NodePort
  selector:
    app: endpoint-frontend
  ports:
    - port: 80
      targetPort: 80
      nodePort: 31080
