CREATE DATABASE IF NOT EXISTS `endpoint_author` DEFAULT CHARACTER SET utf8mb4;
CREATE DATABASE IF NOT EXISTS `endpoint_book` DEFAULT CHARACTER SET utf8mb4;
CREATE DATABASE IF NOT EXISTS `endpoint_home` DEFAULT CHARACTER SET utf8mb4;
CREATE DATABASE IF NOT EXISTS `endpoint_member` DEFAULT CHARACTER SET utf8mb4;
CREATE DATABASE IF NOT EXISTS `endpoint_payorder` DEFAULT CHARACTER SET utf8mb4;
