apiVersion: apps/v1
kind: Deployment
metadata:
  name: endpoint-author
  namespace: endpoint
spec:
  replicas: 1
  selector:
    matchLabels:
      app: endpoint-author
  template:
    metadata:
      labels:
        app: endpoint-author
    spec:
      containers:
        - name: author
          image: 192.168.10.102/xiaoshuowang/author:latest
          ports:
            - containerPort: 10001
          envFrom:
            - secretRef:
                name: endpoint-secrets
            - configMapRef:
                name: endpoint-config
---
apiVersion: v1
kind: Service
metadata:
  name: endpoint-author-svc
  namespace: endpoint
spec:
  selector:
    app: endpoint-author
  ports:
    - port: 10001
      targetPort: 10001
