apiVersion: apps/v1
kind: Deployment
metadata:
  name: endpoint-book
  namespace: endpoint
spec:
  replicas: 1
  selector:
    matchLabels:
      app: endpoint-book
  template:
    metadata:
      labels:
        app: endpoint-book
    spec:
      containers:
        - name: book
          image: 192.168.10.102/xiaoshuowang/book:latest
          ports:
            - containerPort: 10002
          envFrom:
            - configMapRef:
                name: endpoint-config
            - secretRef:
                name: endpoint-secrets
---
apiVersion: v1
kind: Service
metadata:
  name: endpoint-book-svc
  namespace: endpoint
spec:
  selector:
    app: endpoint-book
  ports:
    - port: 10002
      targetPort: 10002
